export const FETCHING_MOVIE_REQUEST = 'FETCHING_MOVIE_REQUEST'
export const FETCHING_MOVIE_SUCCESS = 'FETCHING_MOVIE_SUCCESS'
export const FETCHING_MOVIE_FAILURE = 'FETCHING_MOVIE_FAILURE'
export const FETCHING_REFRESH_SUCCESS = 'FETCHING_REFRESH_SUCCESS'